stages:
  prepare-mnist:
    cmd: cd step1 && python3 prepare_mnist.py
    deps:
    - data/fashion-mnist/t10k-images-idx3-ubyte.gz
    - data/fashion-mnist/t10k-labels-idx1-ubyte.gz
    - data/fashion-mnist/train-images-idx3-ubyte.gz
    - data/fashion-mnist/train-labels-idx1-ubyte.gz
    - step1/prepare_mnist.py
    outs:
    - data/fashion-mnist/test.pickle
    - data/fashion-mnist/train.pickle
  train:
    cmd: cd step1 && python3 train.py --model-dir ../model/
    deps:
    - data/fashion-mnist/test.pickle
    - data/fashion-mnist/train.pickle
    - step1/train-vertex.py
    metrics:
      - metrics.json:
          cache: false
    outs:
      - model/model.joblib
    params:
    - train.n_neighbours
