stages:
  prepare-mnist:
    cmd: cd step2 && python3 prepare_mnist.py
    deps:
    - data/fashion-mnist/t10k-images-idx3-ubyte.gz
    - data/fashion-mnist/t10k-labels-idx1-ubyte.gz
    - data/fashion-mnist/train-images-idx3-ubyte.gz
    - data/fashion-mnist/train-labels-idx1-ubyte.gz
    - step2/prepare_mnist.py
    outs:
    - data/fashion-mnist/test.pickle
    - data/fashion-mnist/train.pickle
  train:
    cmd: cd step2 && python3 train-vertex.py
    deps:
    - data/fashion-mnist/test.pickle
    - data/fashion-mnist/train.pickle
    - step2/train-vertex.py
    metrics:
      - metrics.json:
          cache: false
    outs:
      - model/model.joblib
    params:
    - train.n_neighbours
